[application]
name = "Why I don't mock ðŸ’©"
default_platform = "web"
out_dir = "docs"
asset_dir = "public"

[web.app]
title = "Why I don't mock ðŸ’©"

[web.watcher]
watch_path = ["src", "public"]

[web.resource.dev]
script = [
    "./impress.js"
]
